name: phpunit

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mariadb:
        image: mariadb:latest
        ports:
          - 3306
        env:
          MYSQL_USER: user
          MYSQL_PASSWORD: password
          MYSQL_DATABASE: example_app
          MYSQL_ROOT_PASSWORD: password
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Verify MariaDB connection
        env:
          PORT: ${{ job.services.mariadb.ports[3306] }}
        run: |
          while ! mysqladmin ping -h"127.0.0.1" -P"$PORT" --silent; do
            sleep 1
          done

      - name: Install PHP extensions
        run: sudo apt-get install -y php-phpdbg

      - name: Check phpdbg version
        run: phpdbg -V

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.testing', '.env');"

      - name: Install Composer Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Generate key
        run: php artisan key:generate

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Clear Configuration
        run: php artisan config:clear

      - name: Run the migrations
        run: php artisan migrate

      - name: Run tests via PHPUnit
        env:
          XDEBUG_MODE: coverage
        run: |
          vendor/bin/phpunit --coverage-clover=coverage.xml
          cat ./coverage.xml

      - name: Show coverage.xml
        run: cat ./coverage.xml

      - name: Upload coverage.xml to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          fail_ci_if_error: true
          flags: unittests
          name: codecov-umbrella
          verbose: true
          env_vars: PHP
